export const SET_USER = 'SET_USER'
export const GET_TODO = 'GET_TODO'
export const ADD_TODO = 'ADD_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const GET_TODO_FROM_SERVER = 'GET_TODO_FROM_SERVER'
export const CHANGE_STATUS = 'CHANGE_STATUS'
